[package]
name = "example"
version = "0.1.0"
edition = "2024_07"
discription = ""

[dependencies]
second = {path = "packages/second/" }

[dev-dependencies]
# uncomment the next line to make the project compile
#first = {path = "packages/first/" } 
